In [1]:
add = lambda a : a + 10 #anonim fonksiyon tanımı

print(add(5))

15


In [2]:
sharp = lambda a, b : a * b #birden çok değişken alabilir 

print(sharp(10,12))

120


In [3]:
#def prog(positional arguments, *args , named arguments, **kwargs)
#def prog(10, *args , a = 20 , **kwargs)

In [4]:
res = (lambda *args : sum(args))
res(10,20), res(10,20,30), res(90,91,21354)

(30, 60, 21535)

In [5]:
res1 = (lambda **kwargs : sum(kwargs.values())) #değişken olarak yollanılarak işlem yapmak
res1(a = 100,b = 1000, c = 8281)

9381

In [6]:
#filter(function, iterable), map(function, iterable) , reduce(function, iterable)
list1 = [10,20,30,40,50,60,70,80,90]

def odd(n):
    if n%2 == 0:
        return True
    else:
        return False

odd_num = list(filter(odd , list1))
odd_num

#bir liste ve dizi içerisindeki bütün elemanları tek seferde 
#işlemden geçirip işlem sonuçlarını başka bir listeye aktarma işlemi


[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [7]:
list1 = [1,2,3,4,5,7,8,9]

odd_num = list(filter(lambda n : n%2 == 1, list1))
odd_num
#yukarıdaki işlemin lambda ile yapılımı

[1, 3, 5, 7, 9]

In [8]:
def twice(n):
    return n * 2

doubles = list(map(twice, odd_num)) #liste veya dizideki bütün elemanları bir işlemden geçirir
doubles

[2, 6, 10, 14, 18]

In [9]:
doubles = list(map(lambda n : n*2, odd_num))
doubles

[2, 6, 10, 14, 18]

In [10]:
from functools import reduce

def add(a,b):
    return a+b

sumall = reduce(add, doubles)
sumall

50

In [11]:
sum_all = reduce(lambda a,b : a + b, doubles)
sum_all

50

In [12]:
sum_all = reduce(lambda a,b : a + b, list(map(lambda n : n*2, list(filter(lambda n : n%2 == 1, list1)))))
sum_all # hepsini birlikte kullanmak

50

In [13]:
#Dosyalar

In [14]:
f = open("test_AI.txt", "w")
print(f)

<_io.TextIOWrapper name='test_AI.txt' mode='w' encoding='cp1252'>


In [15]:
f.write("Now is the time")
f.write("\n to close the file")
f.close()

In [16]:
f = open("test_AI2.txt", "r")
text = f.read()
print(text)

Now is the time
 to close the file


In [17]:
f = open("test_AI2.txt", "r")
print(f.read(5))

Now i


In [18]:
print(f.read(1000006))

s the time
 to close the file


In [19]:
fo = open("foo_AI.txt", "w")
fo.write("Python is so basic language.\nSTFU!\n")
fo.close()

In [20]:
fo = open("foo_AI.txt", "r+")
mystr1 = fo.read(17)
print("String is : ", mystr1)

String is :  Python is so basi


In [21]:
position = fo.tell()
print("Cursor location : ", position)

Cursor location :  17


In [22]:
position = fo.seek(0,0)
mystr1 = fo.read(29)
print("New location : ", mystr1)
fo.close()

New location :  Python is so basic language.



In [23]:
try:
    fh = open("test_AI3.txt" , "r")
    fh.write("GKLERJHLGŞENRDŞFOIGBJR ASÖDMHASKLJFHBQEWK ASLDHGOIUERGVFPOJKEDRG OEHFOWIESFJ")
except IOError:
    print("Hata : Dosya bulunamadı yada oluşturulamıyor!")
else:
    print("Dosya başarıyla oluşturuldu ve okundu")


Hata : Dosya bulunamadı yada oluşturulamıyor!


In [24]:
try:
    fh = open("test_AI3.txt" , "w")
    fh.write("lkdjslfksdjfkljsdklfjsdklfjskdlf")
    fh.close()
finally: # her durumun sonunda çağırılır
    print("Hata : Dosya bulunamadı yada oluşturulamıyor!")

Hata : Dosya bulunamadı yada oluşturulamıyor!


In [25]:
#Dicts 'sözlükler'
dict = {'Name' : 'Ayşe', 'Age' : 1, 'Class':'First'}
print(dict['Name'])
print(dict['Age'])

Ayşe
1


In [26]:
del dict['Name']

In [27]:
#Alttaki ile kıyaslandığında numpy ile 3 boyutlu işlemlerde python listelerinden kat ve kat daha hızlı
#olduğunu görüyoruz
import time 
def trad_version():
    t1=time.time()
    X=range(1000000)
    Y=range(1000000)
    Z=[]
    for i in range(len(X)):
        Z.append(X[i]+Y[i])
    return time.time() - t1

trad_version()

0.22212743759155273

In [30]:
#Yukarıdaki kodun numpy versiyonu
import numpy
def numpy_version():
    t1 = time.time()
    X= arange(1000000)
    Y= arange(1000000)
    Z = X+Y
    return time.time()-t1
numpy_version()

NameError: name 'arange' is not defined

In [32]:
#Olası uyarıları gözardı etmek için kullanılır kod her halükarda çalışır
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [33]:
list1 = [10,20,30,40,50,60,70]
list1

[10, 20, 30, 40, 50, 60, 70]

In [34]:
type(list1)

list

In [35]:
#normal bir listeyi numpy listesine çevirmek
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60, 70])

In [36]:
arr1.data #ram deki konumu bulmak

In [37]:
type(arr1)

numpy.ndarray

In [38]:
arr1.dtype#liste içindeki data tipi

dtype('int32')

In [39]:
arr1.astype(float)#liste içi veri tiplerini değiştirme

array([10., 20., 30., 40., 50., 60., 70.])

In [40]:
np.arange(0, 100,10)#belirli aralıkta numpy listesi oluşturma

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.zeros(10)#hazır 10 adet 0 matris üretmek için kullanılır

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.ones(10)#hazır 10 adet 1 matris üretmek için kullanılır

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.repeat(10,5)#10'u 5 kere tekrarlayıp numpy listesi oluşturur

array([10, 10, 10, 10, 10])

In [44]:
a = np.array([10,20,30])
np.repeat(a,3)#ama burda liste içerisindekileri tekrar eder

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [45]:
np.full(5, 10)#tamamen 10 lardan oluşan bir liste oluşturmak

array([10, 10, 10, 10, 10])

In [46]:
ar1 = np.arange(1,20)
ar1[ar1%2 == 1]#liste içindeki tek sayıları bastırma

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [47]:
ar1[ar1%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
np.linspace(10,20,4)#eşit mesafeli sayı üretir

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [49]:
np.random.random(4)#0 ve 1 arasında rasgele değer üretir

array([0.10000554, 0.97551956, 0.64130648, 0.9560397 ])

In [50]:
np.random.randint(0,500,5)#belirtilen aralıkta rasgele sayı üretir

array([439, 288, 419, 300, 444])

In [51]:
np.random.randint(0,500,10)

array([124, 292, 118, 383, 272, 458, 379, 497, 424, 468])

In [52]:
np.random.seed(123)#belirli çekirdek değeri ile sayı üretimi
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [53]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [54]:
f1 = np.random.uniform(5,10, size=(10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [55]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [56]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [57]:
b2 = np.random.randn(10)#ortalaması 0 ver. 1 olan kısacası gauss eğrisi ile liste oluşturulur
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [58]:
arr1

array([10, 20, 30, 40, 50, 60, 70])

In [59]:
#index ve value şeklinde işlemi kısaca yapmak
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60
(6,) 70


In [60]:
#işlemler
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [61]:
arr2.sum()#toplama

190

In [62]:
np.cumsum(arr2)#kendinden öncekileri toplayarak gitme

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [63]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])#2 boyutlu liste yapmak
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [64]:
A.sum(), A.max(), A.min()

(136, 16, 1)

In [65]:
np.amin(A, axis = 0)

array([1, 2, 3, 4])

In [66]:
np.amin(A, axis = 1)

array([ 1,  5,  9, 13])

In [67]:
np.std(A)#standart sapma

4.6097722286464435

In [68]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12
(3, 0) 13
(3, 1) 14
(3, 2) 15
(3, 3) 16


In [69]:
#elemanlara erişim
a= np.array([7,5,3,6,8,9,0,1,2,5])
a[0]

7

In [70]:
a[1:]

array([5, 3, 6, 8, 9, 0, 1, 2, 5])

In [71]:
a[1:4]

array([5, 3, 6])

In [72]:
a[-1]

5

In [73]:
ar = np.arange(1,20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [74]:
rep1 = np.where(ar%2 == 0, 0, ar)#where ile koşullu işlem yapmak
rep1

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19])

In [75]:
ar2 = np.array([10,20,30,10,10,20,20,30,30])
ar2

array([10, 20, 30, 10, 10, 20, 20, 30, 30])

In [76]:
rep2 = np.where(ar2==10,0,ar2)
rep2

array([ 0, 20, 30,  0,  0, 20, 20, 30, 30])

In [77]:
p2 = np.arange(1,500, 40)
p2

array([  1,  41,  81, 121, 161, 201, 241, 281, 321, 361, 401, 441, 481])

In [78]:
np.put(p2,[0,3,5], [33,55,99])#verilen indexlerdeki değerleri verilen değerler ile değiştirme
p2

array([ 33,  41,  81,  55, 161,  99, 241, 281, 321, 361, 401, 441, 481])

In [79]:
#Eksik değerler ile ilgilenme

In [80]:
a = np.array([10, np.nan, 20,30,40, np.nan,90, np.inf])
a

array([10., nan, 20., 30., 40., nan, 90., inf])

In [81]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [82]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 40., 99., 90., inf])

In [83]:
A = np.array([[1,2,3,np.nan],[np.nan,6,7,8],[10,np.nan,12,13],[14,26,71,23]])
A

array([[ 1.,  2.,  3., nan],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 26., 71., 23.]])

In [84]:
np.isnan(A)

array([[False, False, False,  True],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [85]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([3, 0, 1], dtype=int64))