In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
dates = pd.date_range(start = '2022-03-17', end = '2022-03-23')
dates

DatetimeIndex(['2022-03-17', '2022-03-18', '2022-03-19', '2022-03-20',
               '2022-03-21', '2022-03-22', '2022-03-23'],
              dtype='datetime64[ns]', freq='D')

In [2]:
M = np.random.random((7,7))
M

array([[0.59398723, 0.58478375, 0.08401985, 0.65666983, 0.20883153,
        0.14924904, 0.83873501],
       [0.49331251, 0.25649663, 0.04709554, 0.5595868 , 0.74991123,
        0.03243614, 0.39130356],
       [0.1009834 , 0.29744753, 0.92490743, 0.8001383 , 0.98347475,
        0.4160648 , 0.34950317],
       [0.41291801, 0.71033467, 0.86351291, 0.24893839, 0.86627727,
        0.72769451, 0.08463288],
       [0.82339143, 0.8256036 , 0.5212862 , 0.12129172, 0.89537857,
        0.84033354, 0.76043733],
       [0.07021328, 0.90416084, 0.97972252, 0.85685512, 0.14298164,
        0.08044814, 0.887404  ],
       [0.17762588, 0.00136786, 0.59413546, 0.66716015, 0.49575241,
        0.48586961, 0.82783988]])

In [3]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2022-03-17  0.593987  0.584784  0.084020  0.656670  0.208832  0.149249   
2022-03-18  0.493313  0.256497  0.047096  0.559587  0.749911  0.032436   
2022-03-19  0.100983  0.297448  0.924907  0.800138  0.983475  0.416065   
2022-03-20  0.412918  0.710335  0.863513  0.248938  0.866277  0.727695   
2022-03-21  0.823391  0.825604  0.521286  0.121292  0.895379  0.840334   
2022-03-22  0.070213  0.904161  0.979723  0.856855  0.142982  0.080448   
2022-03-23  0.177626  0.001368  0.594135  0.667160  0.495752  0.485870   

                   6  
2022-03-17  0.838735  
2022-03-18  0.391304  
2022-03-19  0.349503  
2022-03-20  0.084633  
2022-03-21  0.760437  
2022-03-22  0.887404  
2022-03-23  0.827840

In [4]:
dframe.columns = ['C1','C2','C3','C4','C5','C6','C7']
dframe

C1        C2        C3        C4        C5        C6  \
2022-03-17  0.593987  0.584784  0.084020  0.656670  0.208832  0.149249   
2022-03-18  0.493313  0.256497  0.047096  0.559587  0.749911  0.032436   
2022-03-19  0.100983  0.297448  0.924907  0.800138  0.983475  0.416065   
2022-03-20  0.412918  0.710335  0.863513  0.248938  0.866277  0.727695   
2022-03-21  0.823391  0.825604  0.521286  0.121292  0.895379  0.840334   
2022-03-22  0.070213  0.904161  0.979723  0.856855  0.142982  0.080448   
2022-03-23  0.177626  0.001368  0.594135  0.667160  0.495752  0.485870   

                  C7  
2022-03-17  0.838735  
2022-03-18  0.391304  
2022-03-19  0.349503  
2022-03-20  0.084633  
2022-03-21  0.760437  
2022-03-22  0.887404  
2022-03-23  0.827840

In [5]:
dframe.index

DatetimeIndex(['2022-03-17', '2022-03-18', '2022-03-19', '2022-03-20',
               '2022-03-21', '2022-03-22', '2022-03-23'],
              dtype='datetime64[ns]', freq='D')

In [6]:
dframe.columns

Index(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7'], dtype='object')

In [7]:
dframe.dtypes

C1    float64
C2    float64
C3    float64
C4    float64
C5    float64
C6    float64
C7    float64
dtype: object

In [8]:
dframe.sort_values(by = 'C1')

C1        C2        C3        C4        C5        C6  \
2022-03-22  0.070213  0.904161  0.979723  0.856855  0.142982  0.080448   
2022-03-19  0.100983  0.297448  0.924907  0.800138  0.983475  0.416065   
2022-03-23  0.177626  0.001368  0.594135  0.667160  0.495752  0.485870   
2022-03-20  0.412918  0.710335  0.863513  0.248938  0.866277  0.727695   
2022-03-18  0.493313  0.256497  0.047096  0.559587  0.749911  0.032436   
2022-03-17  0.593987  0.584784  0.084020  0.656670  0.208832  0.149249   
2022-03-21  0.823391  0.825604  0.521286  0.121292  0.895379  0.840334   

                  C7  
2022-03-22  0.887404  
2022-03-19  0.349503  
2022-03-23  0.827840  
2022-03-20  0.084633  
2022-03-18  0.391304  
2022-03-17  0.838735  
2022-03-21  0.760437

In [9]:
dframe.sort_values(by = 'C1', ascending = False)

C1        C2        C3        C4        C5        C6  \
2022-03-21  0.823391  0.825604  0.521286  0.121292  0.895379  0.840334   
2022-03-17  0.593987  0.584784  0.084020  0.656670  0.208832  0.149249   
2022-03-18  0.493313  0.256497  0.047096  0.559587  0.749911  0.032436   
2022-03-20  0.412918  0.710335  0.863513  0.248938  0.866277  0.727695   
2022-03-23  0.177626  0.001368  0.594135  0.667160  0.495752  0.485870   
2022-03-19  0.100983  0.297448  0.924907  0.800138  0.983475  0.416065   
2022-03-22  0.070213  0.904161  0.979723  0.856855  0.142982  0.080448   

                  C7  
2022-03-21  0.760437  
2022-03-17  0.838735  
2022-03-18  0.391304  
2022-03-20  0.084633  
2022-03-23  0.827840  
2022-03-19  0.349503  
2022-03-22  0.887404

In [10]:
dict = {'A':pd.Series([1,2,3,11], index = ['a','b','c','d']),'B':pd.Series([1,2,3,4],index = ['a','b','c','d'])}
df12 = pd.DataFrame(dict)
df12

A  B
a   1  1
b   2  2
c   3  3
d  11  4

In [11]:
df12.drop(['A'], axis = 1,inplace = True)
df12

B
a  1
b  2
c  3
d  4

In [12]:
col1 = np.linspace(10,100,30)
col2 = np.random.randint(10,100,30)
df10 = pd.DataFrame({'C1':col1,'C2':col2})
df10

C1  C2
0    10.000000  35
1    13.103448  94
2    16.206897  37
3    19.310345  72
4    22.413793  56
5    25.517241  89
6    28.620690  64
7    31.724138  68
8    34.827586  98
9    37.931034  11
10   41.034483  45
11   44.137931  84
12   47.241379  90
13   50.344828  16
14   53.448276  66
15   56.551724  29
16   59.655172  13
17   62.758621  95
18   65.862069  65
19   68.965517  66
20   72.068966  15
21   75.172414  32
22   78.275862  10
23   81.379310  56
24   84.482759  12
25   87.586207  81
26   90.689655  76
27   93.793103  53
28   96.896552  34
29  100.000000  75

In [13]:
df10 = df10.drop([17,18,19], axis = 0)
df10

C1  C2
0    10.000000  35
1    13.103448  94
2    16.206897  37
3    19.310345  72
4    22.413793  56
5    25.517241  89
6    28.620690  64
7    31.724138  68
8    34.827586  98
9    37.931034  11
10   41.034483  45
11   44.137931  84
12   47.241379  90
13   50.344828  16
14   53.448276  66
15   56.551724  29
16   59.655172  13
20   72.068966  15
21   75.172414  32
22   78.275862  10
23   81.379310  56
24   84.482759  12
25   87.586207  81
26   90.689655  76
27   93.793103  53
28   96.896552  34
29  100.000000  75

In [14]:
df10.drop([16],axis = 0,inplace = True)

In [15]:
df10

C1  C2
0    10.000000  35
1    13.103448  94
2    16.206897  37
3    19.310345  72
4    22.413793  56
5    25.517241  89
6    28.620690  64
7    31.724138  68
8    34.827586  98
9    37.931034  11
10   41.034483  45
11   44.137931  84
12   47.241379  90
13   50.344828  16
14   53.448276  66
15   56.551724  29
20   72.068966  15
21   75.172414  32
22   78.275862  10
23   81.379310  56
24   84.482759  12
25   87.586207  81
26   90.689655  76
27   93.793103  53
28   96.896552  34
29  100.000000  75

In [16]:
df10.drop(df10.index[5], inplace = True)
df10

C1  C2
0    10.000000  35
1    13.103448  94
2    16.206897  37
3    19.310345  72
4    22.413793  56
6    28.620690  64
7    31.724138  68
8    34.827586  98
9    37.931034  11
10   41.034483  45
11   44.137931  84
12   47.241379  90
13   50.344828  16
14   53.448276  66
15   56.551724  29
20   72.068966  15
21   75.172414  32
22   78.275862  10
23   81.379310  56
24   84.482759  12
25   87.586207  81
26   90.689655  76
27   93.793103  53
28   96.896552  34
29  100.000000  75

In [17]:
df10 = df10.iloc[3:,]
df10

C1  C2
3    19.310345  72
4    22.413793  56
6    28.620690  64
7    31.724138  68
8    34.827586  98
9    37.931034  11
10   41.034483  45
11   44.137931  84
12   47.241379  90
13   50.344828  16
14   53.448276  66
15   56.551724  29
20   72.068966  15
21   75.172414  32
22   78.275862  10
23   81.379310  56
24   84.482759  12
25   87.586207  81
26   90.689655  76
27   93.793103  53
28   96.896552  34
29  100.000000  75

In [18]:
df10 = df10.iloc[:-4,]
df10

C1  C2
3   19.310345  72
4   22.413793  56
6   28.620690  64
7   31.724138  68
8   34.827586  98
9   37.931034  11
10  41.034483  45
11  44.137931  84
12  47.241379  90
13  50.344828  16
14  53.448276  66
15  56.551724  29
20  72.068966  15
21  75.172414  32
22  78.275862  10
23  81.379310  56
24  84.482759  12
25  87.586207  81

In [19]:
df10 = df10.iloc[:10,]
df10

C1  C2
3   19.310345  72
4   22.413793  56
6   28.620690  64
7   31.724138  68
8   34.827586  98
9   37.931034  11
10  41.034483  45
11  44.137931  84
12  47.241379  90
13  50.344828  16

In [20]:
df10.index[df10['C2'] == 60].tolist()

[]

In [21]:
dframe

C1        C2        C3        C4        C5        C6  \
2022-03-17  0.593987  0.584784  0.084020  0.656670  0.208832  0.149249   
2022-03-18  0.493313  0.256497  0.047096  0.559587  0.749911  0.032436   
2022-03-19  0.100983  0.297448  0.924907  0.800138  0.983475  0.416065   
2022-03-20  0.412918  0.710335  0.863513  0.248938  0.866277  0.727695   
2022-03-21  0.823391  0.825604  0.521286  0.121292  0.895379  0.840334   
2022-03-22  0.070213  0.904161  0.979723  0.856855  0.142982  0.080448   
2022-03-23  0.177626  0.001368  0.594135  0.667160  0.495752  0.485870   

                  C7  
2022-03-17  0.838735  
2022-03-18  0.391304  
2022-03-19  0.349503  
2022-03-20  0.084633  
2022-03-21  0.760437  
2022-03-22  0.887404  
2022-03-23  0.827840

In [22]:
dframe.loc['2022-03-17' : '2022-03-19', ['C1','C7']]

C1        C7
2022-03-17  0.593987  0.838735
2022-03-18  0.493313  0.391304
2022-03-19  0.100983  0.349503

In [23]:
dframe[dframe['C1'] > 0.6]

C1        C2        C3        C4        C5        C6  \
2022-03-21  0.823391  0.825604  0.521286  0.121292  0.895379  0.840334   

                  C7  
2022-03-21  0.760437

In [24]:
dframe['C1'] = 888
dframe

C1        C2        C3        C4        C5        C6        C7
2022-03-17  888  0.584784  0.084020  0.656670  0.208832  0.149249  0.838735
2022-03-18  888  0.256497  0.047096  0.559587  0.749911  0.032436  0.391304
2022-03-19  888  0.297448  0.924907  0.800138  0.983475  0.416065  0.349503
2022-03-20  888  0.710335  0.863513  0.248938  0.866277  0.727695  0.084633
2022-03-21  888  0.825604  0.521286  0.121292  0.895379  0.840334  0.760437
2022-03-22  888  0.904161  0.979723  0.856855  0.142982  0.080448  0.887404
2022-03-23  888  0.001368  0.594135  0.667160  0.495752  0.485870  0.827840

In [25]:
dframe.iat[0,2] = 333
dframe

C1        C2          C3        C4        C5        C6        C7
2022-03-17  888  0.584784  333.000000  0.656670  0.208832  0.149249  0.838735
2022-03-18  888  0.256497    0.047096  0.559587  0.749911  0.032436  0.391304
2022-03-19  888  0.297448    0.924907  0.800138  0.983475  0.416065  0.349503
2022-03-20  888  0.710335    0.863513  0.248938  0.866277  0.727695  0.084633
2022-03-21  888  0.825604    0.521286  0.121292  0.895379  0.840334  0.760437
2022-03-22  888  0.904161    0.979723  0.856855  0.142982  0.080448  0.887404
2022-03-23  888  0.001368    0.594135  0.667160  0.495752  0.485870  0.827840

In [26]:
dframe.iloc[0,2] = 555
dframe

C1        C2          C3        C4        C5        C6        C7
2022-03-17  888  0.584784  555.000000  0.656670  0.208832  0.149249  0.838735
2022-03-18  888  0.256497    0.047096  0.559587  0.749911  0.032436  0.391304
2022-03-19  888  0.297448    0.924907  0.800138  0.983475  0.416065  0.349503
2022-03-20  888  0.710335    0.863513  0.248938  0.866277  0.727695  0.084633
2022-03-21  888  0.825604    0.521286  0.121292  0.895379  0.840334  0.760437
2022-03-22  888  0.904161    0.979723  0.856855  0.142982  0.080448  0.887404
2022-03-23  888  0.001368    0.594135  0.667160  0.495752  0.485870  0.827840

In [27]:
dframe.loc[0:4,'C7'] = np.NaN
dframe.loc[0:2,'C6'] = np.NaN
dframe.loc[5:6,'C5'] = np.NaN

In [28]:
dframe

C1        C2          C3        C4        C5        C6        C7
2022-03-17  888  0.584784  555.000000  0.656670  0.208832       NaN       NaN
2022-03-18  888  0.256497    0.047096  0.559587  0.749911       NaN       NaN
2022-03-19  888  0.297448    0.924907  0.800138  0.983475  0.416065       NaN
2022-03-20  888  0.710335    0.863513  0.248938  0.866277  0.727695       NaN
2022-03-21  888  0.825604    0.521286  0.121292  0.895379  0.840334  0.760437
2022-03-22  888  0.904161    0.979723  0.856855       NaN  0.080448  0.887404
2022-03-23  888  0.001368    0.594135  0.667160  0.495752  0.485870  0.827840

In [29]:
dframe.notna()

C1    C2    C3    C4     C5     C6     C7
2022-03-17  True  True  True  True   True  False  False
2022-03-18  True  True  True  True   True  False  False
2022-03-19  True  True  True  True   True   True  False
2022-03-20  True  True  True  True   True   True  False
2022-03-21  True  True  True  True   True   True   True
2022-03-22  True  True  True  True  False   True   True
2022-03-23  True  True  True  True   True   True   True

In [30]:
dframe.isna()

C1     C2     C3     C4     C5     C6     C7
2022-03-17  False  False  False  False  False   True   True
2022-03-18  False  False  False  False  False   True   True
2022-03-19  False  False  False  False  False  False   True
2022-03-20  False  False  False  False  False  False   True
2022-03-21  False  False  False  False  False  False  False
2022-03-22  False  False  False  False   True  False  False
2022-03-23  False  False  False  False  False  False  False

In [31]:
dframe = dframe.fillna(1020)
dframe

C1        C2          C3        C4           C5           C6  \
2022-03-17  888  0.584784  555.000000  0.656670     0.208832  1020.000000   
2022-03-18  888  0.256497    0.047096  0.559587     0.749911  1020.000000   
2022-03-19  888  0.297448    0.924907  0.800138     0.983475     0.416065   
2022-03-20  888  0.710335    0.863513  0.248938     0.866277     0.727695   
2022-03-21  888  0.825604    0.521286  0.121292     0.895379     0.840334   
2022-03-22  888  0.904161    0.979723  0.856855  1020.000000     0.080448   
2022-03-23  888  0.001368    0.594135  0.667160     0.495752     0.485870   

                     C7  
2022-03-17  1020.000000  
2022-03-18  1020.000000  
2022-03-19  1020.000000  
2022-03-20  1020.000000  
2022-03-21     0.760437  
2022-03-22     0.887404  
2022-03-23     0.827840

In [32]:
dframe.loc[0:4,'C7'] = np.NaN
dframe.loc[0:2,'C6'] = np.NaN
dframe.loc[5:6,'C5'] = np.NaN

In [33]:
dframe

C1        C2          C3        C4        C5        C6        C7
2022-03-17  888  0.584784  555.000000  0.656670  0.208832       NaN       NaN
2022-03-18  888  0.256497    0.047096  0.559587  0.749911       NaN       NaN
2022-03-19  888  0.297448    0.924907  0.800138  0.983475  0.416065       NaN
2022-03-20  888  0.710335    0.863513  0.248938  0.866277  0.727695       NaN
2022-03-21  888  0.825604    0.521286  0.121292  0.895379  0.840334  0.760437
2022-03-22  888  0.904161    0.979723  0.856855       NaN  0.080448  0.887404
2022-03-23  888  0.001368    0.594135  0.667160  0.495752  0.485870  0.827840

In [34]:
dframe.fillna(value = {'C5':123, 'C6':789})

C1        C2          C3        C4          C5          C6  \
2022-03-17  888  0.584784  555.000000  0.656670    0.208832  789.000000   
2022-03-18  888  0.256497    0.047096  0.559587    0.749911  789.000000   
2022-03-19  888  0.297448    0.924907  0.800138    0.983475    0.416065   
2022-03-20  888  0.710335    0.863513  0.248938    0.866277    0.727695   
2022-03-21  888  0.825604    0.521286  0.121292    0.895379    0.840334   
2022-03-22  888  0.904161    0.979723  0.856855  123.000000    0.080448   
2022-03-23  888  0.001368    0.594135  0.667160    0.495752    0.485870   

                  C7  
2022-03-17       NaN  
2022-03-18       NaN  
2022-03-19       NaN  
2022-03-20       NaN  
2022-03-21  0.760437  
2022-03-22  0.887404  
2022-03-23  0.827840

In [35]:
dframe.fillna(value={'C7':789}, limit = 1)

C1        C2          C3        C4        C5        C6  \
2022-03-17  888  0.584784  555.000000  0.656670  0.208832       NaN   
2022-03-18  888  0.256497    0.047096  0.559587  0.749911       NaN   
2022-03-19  888  0.297448    0.924907  0.800138  0.983475  0.416065   
2022-03-20  888  0.710335    0.863513  0.248938  0.866277  0.727695   
2022-03-21  888  0.825604    0.521286  0.121292  0.895379  0.840334   
2022-03-22  888  0.904161    0.979723  0.856855       NaN  0.080448   
2022-03-23  888  0.001368    0.594135  0.667160  0.495752  0.485870   

                    C7  
2022-03-17  789.000000  
2022-03-18         NaN  
2022-03-19         NaN  
2022-03-20         NaN  
2022-03-21    0.760437  
2022-03-22    0.887404  
2022-03-23    0.827840

In [36]:
dframe.dropna()

C1        C2        C3        C4        C5        C6        C7
2022-03-21  888  0.825604  0.521286  0.121292  0.895379  0.840334  0.760437
2022-03-23  888  0.001368  0.594135  0.667160  0.495752  0.485870  0.827840

In [37]:
dframe.dropna(axis = 'columns')

C1        C2          C3        C4
2022-03-17  888  0.584784  555.000000  0.656670
2022-03-18  888  0.256497    0.047096  0.559587
2022-03-19  888  0.297448    0.924907  0.800138
2022-03-20  888  0.710335    0.863513  0.248938
2022-03-21  888  0.825604    0.521286  0.121292
2022-03-22  888  0.904161    0.979723  0.856855
2022-03-23  888  0.001368    0.594135  0.667160

In [38]:
dframe.fillna(55, inplace = True)
dframe

C1        C2          C3        C4         C5         C6  \
2022-03-17  888  0.584784  555.000000  0.656670   0.208832  55.000000   
2022-03-18  888  0.256497    0.047096  0.559587   0.749911  55.000000   
2022-03-19  888  0.297448    0.924907  0.800138   0.983475   0.416065   
2022-03-20  888  0.710335    0.863513  0.248938   0.866277   0.727695   
2022-03-21  888  0.825604    0.521286  0.121292   0.895379   0.840334   
2022-03-22  888  0.904161    0.979723  0.856855  55.000000   0.080448   
2022-03-23  888  0.001368    0.594135  0.667160   0.495752   0.485870   

                   C7  
2022-03-17  55.000000  
2022-03-18  55.000000  
2022-03-19  55.000000  
2022-03-20  55.000000  
2022-03-21   0.760437  
2022-03-22   0.887404  
2022-03-23   0.827840

In [39]:
dframe.mean()

C1    888.000000
C2      0.511456
C3     79.847237
C4      0.558663
C5      8.457089
C6     16.078630
C7     31.782240
dtype: float64

In [40]:
dframe.max()

C1    888.000000
C2      0.904161
C3    555.000000
C4      0.856855
C5     55.000000
C6     55.000000
C7     55.000000
dtype: float64

In [41]:
dframe.min()

C1    888.000000
C2      0.001368
C3      0.047096
C4      0.121292
C5      0.208832
C6      0.080448
C7      0.760437
dtype: float64

In [42]:
dframe.std()

C1      0.000000
C2      0.333874
C3    209.522918
C4      0.275629
C5     20.525247
C6     26.589456
C7     28.957657
dtype: float64

In [43]:
dframe.sum()

C1    6216.000000
C2       3.580195
C3     558.930660
C4       3.910640
C5      59.199626
C6     112.550411
C7     222.475681
dtype: float64

In [44]:
dframe.describe()

C1        C2          C3        C4         C5         C6         C7
count    7.0  7.000000    7.000000  7.000000   7.000000   7.000000   7.000000
mean   888.0  0.511456   79.847237  0.558663   8.457089  16.078630  31.782240
std      0.0  0.333874  209.522918  0.275629  20.525247  26.589456  28.957657
min    888.0  0.001368    0.047096  0.121292   0.208832   0.080448   0.760437
25%    888.0  0.276972    0.557711  0.404263   0.622832   0.450967   0.857622
50%    888.0  0.584784    0.863513  0.656670   0.866277   0.727695  55.000000
75%    888.0  0.767969    0.952315  0.733649   0.939427  27.920167  55.000000
max    888.0  0.904161  555.000000  0.856855  55.000000  55.000000  55.000000

In [45]:
dframe.apply(max)

C1    888.000000
C2      0.904161
C3    555.000000
C4      0.856855
C5     55.000000
C6     55.000000
C7     55.000000
dtype: float64

In [46]:
dframe.applymap(np.sqrt)

C1        C2         C3        C4        C5        C6  \
2022-03-17  29.799329  0.764712  23.558438  0.810352  0.456981  7.416198   
2022-03-18  29.799329  0.506455   0.217015  0.748055  0.865974  7.416198   
2022-03-19  29.799329  0.545388   0.961721  0.894504  0.991703  0.645031   
2022-03-20  29.799329  0.842814   0.929254  0.498937  0.930740  0.853050   
2022-03-21  29.799329  0.908627   0.722002  0.348270  0.946244  0.916697   
2022-03-22  29.799329  0.950874   0.989809  0.925665  7.416198  0.283634   
2022-03-23  29.799329  0.036985   0.770802  0.816799  0.704097  0.697043   

                  C7  
2022-03-17  7.416198  
2022-03-18  7.416198  
2022-03-19  7.416198  
2022-03-20  7.416198  
2022-03-21  0.872031  
2022-03-22  0.942021  
2022-03-23  0.909857

In [47]:
dframe

C1        C2          C3        C4         C5         C6  \
2022-03-17  888  0.584784  555.000000  0.656670   0.208832  55.000000   
2022-03-18  888  0.256497    0.047096  0.559587   0.749911  55.000000   
2022-03-19  888  0.297448    0.924907  0.800138   0.983475   0.416065   
2022-03-20  888  0.710335    0.863513  0.248938   0.866277   0.727695   
2022-03-21  888  0.825604    0.521286  0.121292   0.895379   0.840334   
2022-03-22  888  0.904161    0.979723  0.856855  55.000000   0.080448   
2022-03-23  888  0.001368    0.594135  0.667160   0.495752   0.485870   

                   C7  
2022-03-17  55.000000  
2022-03-18  55.000000  
2022-03-19  55.000000  
2022-03-20  55.000000  
2022-03-21   0.760437  
2022-03-22   0.887404  
2022-03-23   0.827840

In [48]:
import math
dframe.applymap(math.sqrt)

C1        C2         C3        C4        C5        C6  \
2022-03-17  29.799329  0.764712  23.558438  0.810352  0.456981  7.416198   
2022-03-18  29.799329  0.506455   0.217015  0.748055  0.865974  7.416198   
2022-03-19  29.799329  0.545388   0.961721  0.894504  0.991703  0.645031   
2022-03-20  29.799329  0.842814   0.929254  0.498937  0.930740  0.853050   
2022-03-21  29.799329  0.908627   0.722002  0.348270  0.946244  0.916697   
2022-03-22  29.799329  0.950874   0.989809  0.925665  7.416198  0.283634   
2022-03-23  29.799329  0.036985   0.770802  0.816799  0.704097  0.697043   

                  C7  
2022-03-17  7.416198  
2022-03-18  7.416198  
2022-03-19  7.416198  
2022-03-20  7.416198  
2022-03-21  0.872031  
2022-03-22  0.942021  
2022-03-23  0.909857

In [49]:
dframe.applymap(float)

C1        C2          C3        C4         C5         C6  \
2022-03-17  888.0  0.584784  555.000000  0.656670   0.208832  55.000000   
2022-03-18  888.0  0.256497    0.047096  0.559587   0.749911  55.000000   
2022-03-19  888.0  0.297448    0.924907  0.800138   0.983475   0.416065   
2022-03-20  888.0  0.710335    0.863513  0.248938   0.866277   0.727695   
2022-03-21  888.0  0.825604    0.521286  0.121292   0.895379   0.840334   
2022-03-22  888.0  0.904161    0.979723  0.856855  55.000000   0.080448   
2022-03-23  888.0  0.001368    0.594135  0.667160   0.495752   0.485870   

                   C7  
2022-03-17  55.000000  
2022-03-18  55.000000  
2022-03-19  55.000000  
2022-03-20  55.000000  
2022-03-21   0.760437  
2022-03-22   0.887404  
2022-03-23   0.827840

In [50]:
dframe.apply(lambda x : min(x))

C1    888.000000
C2      0.001368
C3      0.047096
C4      0.121292
C5      0.208832
C6      0.080448
C7      0.760437
dtype: float64

In [51]:
dframe.apply(lambda x : x*x)

C1        C2             C3        C4           C5  \
2022-03-17  788544  0.341972  308025.000000  0.431215     0.043611   
2022-03-18  788544  0.065791       0.002218  0.313137     0.562367   
2022-03-19  788544  0.088475       0.855454  0.640221     0.967223   
2022-03-20  788544  0.504575       0.745655  0.061970     0.750436   
2022-03-21  788544  0.681621       0.271739  0.014712     0.801703   
2022-03-22  788544  0.817507       0.959856  0.734201  3025.000000   
2022-03-23  788544  0.000002       0.352997  0.445103     0.245770   

                     C6           C7  
2022-03-17  3025.000000  3025.000000  
2022-03-18  3025.000000  3025.000000  
2022-03-19     0.173110  3025.000000  
2022-03-20     0.529539  3025.000000  
2022-03-21     0.706160     0.578265  
2022-03-22     0.006472     0.787486  
2022-03-23     0.236069     0.685319

In [52]:
daf1 = pd.DataFrame({'id':['1','2','3','4','5'], 'Name':['Dogu','Mehmet','Ali','Ahmet','Brad']})
daf1

id    Name
0  1    Dogu
1  2  Mehmet
2  3     Ali
3  4   Ahmet
4  5    Brad

In [53]:
daf2 = pd.DataFrame({'id':['1','2','6','7','8'], 'Score':[40,60,100,190,100]})
daf2

id  Score
0  1     40
1  2     60
2  6    100
3  7    190
4  8    100

In [54]:
pd.merge(daf1 , daf2 , on='id' , how='inner')

id    Name  Score
0  1    Dogu     40
1  2  Mehmet     60

In [55]:
pd.merge(daf1,daf2,on='id',how='outer')

id    Name  Score
0  1    Dogu   40.0
1  2  Mehmet   60.0
2  3     Ali    NaN
3  4   Ahmet    NaN
4  5    Brad    NaN
5  6     NaN  100.0
6  7     NaN  190.0
7  8     NaN  100.0

In [56]:
pd.merge(daf1,daf2,on='id',how='left')

id    Name  Score
0  1    Dogu   40.0
1  2  Mehmet   60.0
2  3     Ali    NaN
3  4   Ahmet    NaN
4  5    Brad    NaN

In [57]:
pd.merge(daf1,daf2,on='id',how='right')

id    Name  Score
0  1    Dogu     40
1  2  Mehmet     60
2  6     NaN    100
3  7     NaN    190
4  8     NaN    100

In [58]:
covid = pd.read_csv('covid19.csv')
covid.head(10)

FIPS  Admin2  Province_State  \
0                                                NaN     NaN             NaN   
1                                                NaN     NaN             NaN   
2                                                NaN     NaN             NaN   
3                                                NaN     NaN             NaN   
4                                                NaN     NaN             NaN   
5                                                NaN     NaN             NaN   
6                                                NaN     NaN             NaN   
7                                                NaN     NaN             NaN   
8                                                NaN     NaN             NaN   
9  ,,Australian Capital Territory,Australia,2022-...     NaN             NaN   

        Country_Region          Last_Update       Lat      Long_  Confirmed  \
0          Afghanistan  2022-04-25 04:20:56  33.93911  67.709953   178689.0   
1              Albania  2022-04-25 04:20:56  41.15330  20.168300   274828.0   
2              Algeria  2022-04-25 04:20:56  28.03390   1.659600   265767.0   
3              Andorra  2022-04-25 04:20:56  42.50630   1.521800    41013.0   
4               Angola  2022-04-25 04:20:56 -11.20270  17.873900    99287.0   
5           Antarctica  2022-04-25 04:20:56 -71.94990  23.347000       11.0   
6  Antigua and Barbuda  2022-04-25 04:20:56  17.06080 -61.796400     7571.0   
7            Argentina  2022-04-25 04:20:56 -38.41610 -63.616700  9060923.0   
8              Armenia  2022-04-25 04:20:56  40.06910  45.038200   422825.0   
9                  NaN                  NaN       NaN        NaN        NaN   

     Deaths  Recovered  Active         Combined_Key  Incident_Rate  \
0    7682.0        NaN     NaN          Afghanistan     459.020332   
1    3496.0        NaN     NaN              Albania    9549.933977   
2    6875.0        NaN     NaN              Algeria     606.067682   
3     153.0        NaN     NaN              Andorra   53080.955154   
4    1900.0        NaN     NaN               Angola     302.093928   
5       0.0        NaN     NaN           Antarctica            NaN   
6     135.0        NaN     NaN  Antigua and Barbuda    7731.190262   
7  128344.0        NaN     NaN            Argentina   20048.162907   
8    8622.0        NaN     NaN              Armenia   14269.038490   
9       NaN        NaN     NaN                  NaN            NaN   

   Case_Fatality_Ratio  
0             4.299089  
1             1.272068  
2             2.586852  
3             0.373052  
4             1.913644  
5             0.000000  
6             1.783120  
7             1.416456  
8             2.039141  
9                  NaN

In [59]:
covid.tail(10)

FIPS  Admin2  Province_State        Country_Region          Last_Update  \
4000  NaN     NaN             NaN               Uruguay  2022-04-25 04:20:56   
4001  NaN     NaN             NaN            Uzbekistan  2022-04-25 04:20:56   
4002  NaN     NaN             NaN               Vanuatu  2022-04-25 04:20:56   
4003  NaN     NaN             NaN             Venezuela  2022-04-25 04:20:56   
4004  NaN     NaN             NaN               Vietnam  2022-04-25 04:20:56   
4005  NaN     NaN             NaN    West Bank and Gaza  2022-04-25 04:20:56   
4006  NaN     NaN             NaN  Winter Olympics 2022  2022-04-25 04:20:56   
4007  NaN     NaN             NaN                 Yemen  2022-04-25 04:20:56   
4008  NaN     NaN             NaN                Zambia  2022-04-25 04:20:56   
4009  NaN     NaN             NaN              Zimbabwe  2022-04-25 04:20:56   

            Lat       Long_   Confirmed   Deaths  Recovered  Active  \
4000 -32.522800  -55.765800    895775.0   7197.0        NaN     NaN   
4001  41.377491   64.585262    238469.0   1637.0        NaN     NaN   
4002 -15.376700  166.959200      6840.0     12.0        NaN     NaN   
4003   6.423800  -66.589700    522176.0   5706.0        NaN     NaN   
4004  14.058324  108.277199  10563502.0  43013.0        NaN     NaN   
4005  31.952200   35.233200    656876.0   5657.0        NaN     NaN   
4006  39.904200  116.407400       535.0      0.0        NaN     NaN   
4007  15.552727   48.516388     11818.0   2149.0        NaN     NaN   
4008 -13.133897   27.849332    318984.0   3974.0        NaN     NaN   
4009 -19.015438   29.154857    247524.0   5468.0        NaN     NaN   

              Combined_Key  Incident_Rate  Case_Fatality_Ratio  
4000               Uruguay   25787.144470             0.803438  
4001            Uzbekistan     712.502860             0.686462  
4002               Vanuatu    2337.023370             0.175439  
4003             Venezuela    1836.323838             1.092735  
4004               Vietnam   10852.327694             0.407185  
4005    West Bank and Gaza   12876.346489             0.861198  
4006  Winter Olympics 2022            NaN             0.000000  
4007                 Yemen      39.623190            18.184126  
4008                Zambia    1735.121646             1.245831  
4009              Zimbabwe    1665.378562             2.209079

In [60]:
covid['Country_Region'].unique() 

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', nan,
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Diamond Princess', 'Djibouti', 'Dominica', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Holy See', 'Honduras', '

In [61]:
covid['Country_Region'].nunique()

175

In [62]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4010 entries, 0 to 4009
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   FIPS                 3835 non-null   object 
 1   Admin2               0 non-null      float64
 2   Province_State       0 non-null      float64
 3   Country_Region       175 non-null    object 
 4   Last_Update          175 non-null    object 
 5   Lat                  173 non-null    float64
 6   Long_                173 non-null    float64
 7   Confirmed            175 non-null    float64
 8   Deaths               175 non-null    float64
 9   Recovered            0 non-null      float64
 10  Active               0 non-null      float64
 11  Combined_Key         175 non-null    object 
 12  Incident_Rate        170 non-null    float64
 13  Case_Fatality_Ratio  175 non-null    float64
dtypes: float64(10), object(4)
memory usage: 438.7+ KB


In [63]:
covid['Country_Region'].head(10)

0            Afghanistan
1                Albania
2                Algeria
3                Andorra
4                 Angola
5             Antarctica
6    Antigua and Barbuda
7              Argentina
8                Armenia
9                    NaN
Name: Country_Region, dtype: object

In [64]:
df1 = covid[['Country_Region','Province_State','Confirmed','Last_Update']]
df1.head(10)

Country_Region  Province_State  Confirmed          Last_Update
0          Afghanistan             NaN   178689.0  2022-04-25 04:20:56
1              Albania             NaN   274828.0  2022-04-25 04:20:56
2              Algeria             NaN   265767.0  2022-04-25 04:20:56
3              Andorra             NaN    41013.0  2022-04-25 04:20:56
4               Angola             NaN    99287.0  2022-04-25 04:20:56
5           Antarctica             NaN       11.0  2022-04-25 04:20:56
6  Antigua and Barbuda             NaN     7571.0  2022-04-25 04:20:56
7            Argentina             NaN  9060923.0  2022-04-25 04:20:56
8              Armenia             NaN   422825.0  2022-04-25 04:20:56
9                  NaN             NaN        NaN                  NaN

In [65]:
df1.loc[df1['Country_Region']=='Argentina']

Country_Region  Province_State  Confirmed          Last_Update
7      Argentina             NaN  9060923.0  2022-04-25 04:20:56

In [66]:
for index, row in df1.iterrows():
    if(row['Country_Region'] == 'Venezuela'):
        display(row[['Country_Region','Confirmed']])

Country_Region    Venezuela
Confirmed          522176.0
Name: 4003, dtype: object

In [67]:
""""
Temel Fonksiyonlar : scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.interpolation
scipyifftpack, scipy.signal, scipy.spatial, scipy.stats, scipy.ndimage, scipy.io
"""
import scipy as sp

In [68]:
import numpy as np
from scipy import linalg

In [69]:
A = np.array([[1,2],[3,4]])
print(A)
B = linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [70]:
A = np.array([[1,2],[3,4]])
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [71]:
X = np.array([[1,3,5],[2,5,1],[2,3,8]])
print(X)
y = np.array([[10],[8],[3]])
print(y)
print('Matris tersi ile denklem çözümü \n', linalg.inv(X).dot(y))
print('Solve fonksiyonu ile çözüm \n', linalg.solve(X,y)) # Hızlı yol

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
Matris tersi ile denklem çözümü 
 [[-9.28]
 [ 5.16]
 [ 0.76]]
Solve fonksiyonu ile çözüm 
 [[-9.28]
 [ 5.16]
 [ 0.76]]


In [72]:
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2,0,6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [75]:
from scipy.misc import derivative
def f(x):
    return x**3 + x**2
D = derivative(f,1.0, dx = 1e-6)
print(D)

4.999999999921734
